/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: addons
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-06-12
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const addonSchema = new Schema(
  {
    _id: mongoose.ObjectId,
    category: String,
    name: String,
    description: String,
    monthlyFee: Number,
    detailUrl: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'addons' },
);

export const Addon = model('Addon', addonSchema);
