/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: addons
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-06-12
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const addonSchema = new Schema(
  {
    category: { type: String, required: true },
    name: { type: String, required: true },
    description: String,
    monthlyFee: { type: Number, default: 0 },
    detailUrl: String,
  },
  { collection: 'addons', timestamps: true },
);

export const Addon = model('Addon', addonSchema);
