/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: plans
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-06-12
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const planSchema = new Schema(
  {
    category: { type: String, required: true },
    name: { type: String, required: true },
    description: String,
    isPopular: { type: Boolean, default: false },
    dataGb: { type: Number, default: 0 },
    sharedDataGb: { type: Number, default: 0 },
    voiceMinutes: { type: Number, default: 0 },
    addonVoiceMinutes: { type: Number, default: 0 },
    smsCount: { type: Number, default: 0 },
    monthlyFee: { type: Number, default: 0 },
    optionalDiscountAmount: { type: Number, default: 0 },
    premiumDiscountAmount: { type: Number, default: 0 },
    ageGroup: { type: String, required: true },
    detailUrl: String,
    bundleBenefit: {
      type: String, // 객체 또는 문자열 모두 지원
      default: null,
    },
    mediaAddons: { type: String, default: null },
    premiumAddons: { type: String, default: null },
    basicService: String,
  },
  { collection: 'plans', timestamps: true },
);

export const Plan = model('Plan', planSchema);
