/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: plans
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-06-12
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const planSchema = new Schema(
  {
    category: { type: String, required: true },
    name: { type: String, required: true },
    description: String,
    monthlyFee: { type: Number, default: 0 },
    detailUrl: String,
    isPopular: { type: Boolean, default: false },
    dataGb: { type: Number, default: 0 },
    sharedDataGb: { type: Number, default: 0 },
    voiceMinutes: { type: Number, default: 0 },
    smsCount: { type: Number, default: 0 },
    bundleBenefit: {
      type: {
        _id: { type: mongoose.Schema.Types.ObjectId, required: true },
        name: { type: String, required: true },
        description: String,
      },
    },
    optionalDiscountAmount: { type: Number, default: 0 },
    premiumDiscountAmount: { type: Number, default: 0 },
    ageGroup: { type: String, required: true },
  },
  { collection: 'plans', timestamps: true },
);

export const Plan = model('Plan', planSchema);
