/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: plansAddons
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-06-12
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const planAddonSchema = new Schema(
  {
    addon: { type: mongoose.ObjectId, require: true },
    plan: { type: mongoose.ObjectId, require: true },
  },
  { collection: 'plansAddons', timestamps: true },
);

export const PlanAddon = model('PlanAddon', planAddonSchema);
